<?php

namespace App\Support;

class Blogs
{
    /**
     * @return array<int, array{title: string, slug: string, description: string, component: string, featured_image: string, featured_image_webp: string, featured_image_alt: string}>
     */
    public static function get(): array
    {
        return [
            [
                'title' => 'Stress verminderen door te sporten',
                'slug' => 'stress-verminderen-door-te-sporten',
                'description' => 'Sporten gaat vaak als eerste ten koste van stress en tijdsdruk, terwijl sporten naast fysieke voordelen ook voor je mentale gezondheid bevorderend is. Het vermindert namelijk stress. Daarom is het van belang om te blijven sporten, ook als je druk bent en juist veel stress ervaart.',
                'component' => 'StressVerminderenDoorTeSporten',
                'featured_image' => '/assets/blog/stress-verminderen.jpg',
                'featured_image_webp' => '/assets/blog/webp/stress-verminderen.webp',
                'featured_image_alt' => 'Stress verminderen door te sporten',
            ],
            [
                'title' => 'Intermittent fasting',
                'slug' => 'intermittent-fasting',
                'description' => 'Een populaire nieuwe methode om af te vallen is intermittent fasting, ofwel periodiek vasten genoemd. Doordat deze methode nog relatief nieuw is zijn er weinig gegevens bekend over de gezondheidsrisico\'s of gezondheidswinst op de lange termijn. Toch zien we deze methode steeds vaker voorkomen. Wat houd intermittent fasting in en waarom komt deze methode van diëten steeds meer voor?',
                'component' => 'IntermittentFasting',
                'featured_image' => '/assets/blog/intermittent-fasting.jpg',
                'featured_image_webp' => '/assets/blog/webp/intermittent-fasting.webp',
                'featured_image_alt' => 'Intermittent fasting',
            ],
            [
                'title' => 'Het belang van eiwitten',
                'slug' => 'het-belang-van-eiwitten',
                'description' => 'Eiwitten, koolhydraten en vetten vormen samen de macronutriënten. Ieder hebben ze hun eigen belang en werking. Voor een gezond voedingspatroon is het ook van belang dat deze macronutriënten in balans zijn. In deze blog gaan we eiwitten behandelen. Wat zijn eiwitten precies, en waarom zijn ze zo belangrijk in ons voedingspatroon.',
                'component' => 'HetBelangVanEiwitten',
                'featured_image' => '/assets/blog/eiwitten.jpg',
                'featured_image_webp' => '/assets/blog/webp/eiwitten.webp',
                'featured_image_alt' => 'Het belang van eiwitten',
            ],
            [
                'title' => 'Cardio of krachttraining?',
                'slug' => 'cardio-of-krachttraining',
                'description' => 'Een eeuwige discussie die geen eenduidig antwoord heeft. Beide hebben namelijk hun voordelen en kunnen beide gebruikt worden om vet te verliezen. Natuurlijk zitten er wel verschillen tussen. Deze verschillen bepalen welke keuze jij het beste kunt maken.',
                'component' => 'CardioOfKrachttraining',
                'featured_image' => '/assets/blog/cardio-of-kracht.jpg',
                'featured_image_webp' => '/assets/blog/webp/cardio-of-kracht.webp',
                'featured_image_alt' => 'Cardio of krachttraining?',
            ],
            [
                'title' => 'Kun je trainen als je spierpijn hebt?',
                'slug' => 'trainen-met-spierpijn',
                'description' => 'Je hebt een hele zware workout gedaan waarvan je dagenlang nog last hebt. Het is inmiddels een paar dagen later en je was eigenlijk van plan om weer te gaan trainen. Is dit dan wel verstandig als je nog spierpijn hebt van de vorige training?',
                'component' => 'TrainenMetSpierpijn',
                'featured_image' => '/assets/blog/kun-je-trainen-als-je-spierpijn-hebt.jpg',
                'featured_image_webp' => '/assets/blog/webp/kun-je-trainen-als-je-spierpijn-hebt.webp',
                'featured_image_alt' => 'Kun je trainen als je spierpijn hebt?',
            ],
            [
                'title' => 'Vet omzetten in spier: is het mogelijk?',
                'slug' => 'vet-omzetten-in-spiermassa',
                'description' => 'We horen vaak voorbij komen dat mensen vet willen omzetten in spiermassa. De vraag is echter of dit überhaupt wel mogelijk is? Dit antwoord is heel kort en eenvoudig: Nee. Het is niet mogelijk om je vet om te zetten in spieren omdat dit twee verschillende processen zijn.',
                'component' => 'VetOmzettenInSpiermassa',
                'featured_image' => '/assets/blog/vet-omzetten.jpeg',
                'featured_image_webp' => '/assets/blog/webp/vet-omzetten.webp',
                'featured_image_alt' => 'Vet omzetten in spiermassa',
            ],
            [
                'title' => 'Sporten met reuma',
                'slug' => 'sporten-met-reuma',
                'description' => 'Meer dan 2 miljoen mensen in Nederland hebben last van reuma. Vaak denken mensen dat krachttraining niet mag als je reuma hebt. Dit zou immers slecht zijn voor je gewrichten. De vraag is echter of dit wel juist is.',
                'component' => 'SportenMetReuma',
                'featured_image' => '/assets/blog/sporten-met-reuma.jpg',
                'featured_image_webp' => '/assets/blog/webp/sporten-met-reuma.webp',
                'featured_image_alt' => 'Sporten met reuma',
            ],
            [
                'title' => 'Het jojo-effect',
                'slug' => 'het-jojo-effect',
                'description' => 'Je zult er weleens van gehoord hebben of misschien zelfs weleens zelf meegemaakt hebben. Iemand is heel veel kilo\'s afgevallen in korte tijd, maar komt daarna ook heel snel deze kilo\'s weer aan.',
                'component' => 'HetJojoEffect',
                'featured_image' => '/assets/blog/het-jojo-effect.jpg',
                'featured_image_webp' => '/assets/blog/webp/het-jojo-effect.webp',
                'featured_image_alt' => 'Het jojo-effect',
            ],
            [
                'title' => 'Hoe snel kun je spiermassa verliezen',
                'slug' => 'snelheid-verlies-spiermassa',
                'description' => 'Het kan weleens voorkomen dat je een tijdje niet kunt trainen. Dit kan zijn door vakantie, blessures of de huidige lockdowns voor de sportscholen. Hoe graag je het ook wilt, er komen periodes dat je niet of minder kunt trainen dan je zou willen.',
                'component' => 'SnelheidVerliesSpiermassa',
                'featured_image' => '/assets/blog/snelheid-verlies-spiermassa.jpg',
                'featured_image_webp' => '/assets/blog/webp/snelheid-verlies-spiermassa.webp',
                'featured_image_alt' => 'Hoe snel kun je spiermassa verliezen',
            ],
            [
                'title' => 'Slaaptekort inhalen',
                'slug' => 'slaaptekort-inhalen',
                'description' => 'Je hoort regelmatig dat mensen last van slaaptekort hebben. Dit kan door verschillende redenen zijn ontstaan. Wellicht had je een leuk feest of heb je net een belangrijk week achter de rug voor je studie of werk.',
                'component' => 'SlaaptekortInhalen',
                'featured_image' => '/assets/blog/slaaptekort-inhalen.jpg',
                'featured_image_webp' => '/assets/blog/webp/slaaptekort-inhalen.webp',
                'featured_image_alt' => 'Slaaptekort inhalen',
            ],
            [
                'title' => 'Het nut van een rustdag',
                'slug' => 'nut-rustdag',
                'description' => 'Rustdagen; voor de één een geschenk uit de hemel, voor de ander iets wat ze liever niet doen. Je hoort weleens mensen zeggen dat rustdagen niet nodig zijn. Hoe vaker je traint, hoe beter toch?',
                'component' => 'NutRustdag',
                'featured_image' => '/assets/blog/nut-rustdag.jpg',
                'featured_image_webp' => '/assets/blog/webp/nut-rustdag.webp',
                'featured_image_alt' => 'Het nut van een rustdag',
            ],
            [
                'title' => 'Detoxen: ja of nee?',
                'slug' => 'detoxen',
                'description' => 'Detoxen neemt de laatste enorm toe in populariteit. Het word om verschillende reden en op verschillende manieren gebruikt. De groente-en fruitsapjes vliegen je tegenwoordig om de oren. Maar is detoxen dan daadwerkelijk zo gezond en effectief?',
                'component' => 'Detoxen',
                'featured_image' => '/assets/blog/detoxen.jpg',
                'featured_image_webp' => '/assets/blog/webp/detoxen.webp',
                'featured_image_alt' => 'Detoxen: ja of nee?',
            ],
            [
                'title' => 'Bulken en cutten',
                'slug' => 'bulken-en-cutten',
                'description' => 'Als je spiermassa wilt creëren, omdat je dat mooi vind of omdat je gewicht wilt verhogen zonder vet aan te komen, kun je het beste gebruik maken van bulken en cutten.',
                'component' => 'BulkenEnCutten',
                'featured_image' => '/assets/blog/bulken-en-cutten.jpg',
                'featured_image_webp' => '/assets/blog/webp/bulken-en-cutten.webp',
                'featured_image_alt' => 'Bulken en cutten',
            ],
            [
                'title' => 'Sporten tijdens en na zwangerschap',
                'slug' => 'sporten-tijdens-en-na-zwangerschap',
                'description' => 'Tijdens de zwangerschap verandert er veel in het lichaam van een vrouw. Dit heeft ook invloed op het sporten. Veel vrouwen vragen zich af wat ze nog kunnen of mogen doen tijdens en na de zwangerschap qua sporten.',
                'component' => 'SportenTijdensEnNaZwangerschap',
                'featured_image' => '/assets/blog/zwangerschap.jpg',
                'featured_image_webp' => '/assets/blog/webp/zwangerschap.webp',
                'featured_image_alt' => 'Sporten tijdens en na zwangerschap',
            ],
            [
                'title' => 'Wat is creatine en hoe werkt het?',
                'slug' => 'werking-creatine',
                'description' => 'Creatine is een supplement dat door veel krachtsporters wordt gebruikt. Maar wat is creatine eigenlijk en wat doet het met ons wanneer we het supplementeren?',
                'component' => 'WerkingCreatine',
                'featured_image' => '/assets/blog/werking-creatine.jpg',
                'featured_image_webp' => '/assets/blog/webp/werking-creatine.webp',
                'featured_image_alt' => 'Creatine',
            ],
            [
                'title' => 'Omega 3 vetzuren: waarom zo populair?',
                'slug' => 'omega-3-vetzuren',
                'description' => 'Omega 3 vetzuren worden steeds populairder. Veel suppletie aanbieders hebben deze vorm van meervoudige onverzadigde vetzuren in hun assortiment. Waarom is deze omega 3 vetzuur zo populair en wat het is eigenlijk?',
                'component' => 'Omega3Vetzuren',
                'featured_image' => '/assets/blog/omega-3-vetzuren.jpg',
                'featured_image_webp' => '/assets/blog/webp/omega-3-vetzuren.webp',
                'featured_image_alt' => 'Omega 3 vetzuren',
            ],
            [
                'title' => 'Fatburners: makkelijk afvallen of onverstandig?',
                'slug' => 'fatburners',
                'description' => 'Nadat we al een blog hebben geschreven over creatine en omega 3 vetzuren volgt nu een blog over fatburners. Wat is nu eigenlijk een fatburner?',
                'component' => 'Fatburners',
                'featured_image' => '/assets/blog/fatburners.jpg',
                'featured_image_webp' => '/assets/blog/webp/fatburners.webp',
                'featured_image_alt' => 'Fatburners',
            ],
            [
                'title' => 'Dilemma: afvallen en de overgang!',
                'slug' => 'afvallen-en-overgang',
                'description' => 'We krijgen veel vragen van vrouwen die in de overgang zitten. Het afvalproces gaat moeizaam en ze weten niet wat te doen. In deze blog lees je er meer over!',
                'component' => 'AfvallenEnOvergang',
                'featured_image' => '/assets/blog/afvallen-en-overgang.jpg',
                'featured_image_webp' => '/assets/blog/webp/afvallen-en-overgang.webp',
                'featured_image_alt' => 'Afvallen en de overgang',
            ],
            [
                'title' => 'Gaan alcohol en afvallen samen?',
                'slug' => 'alcohol-en-afvallen',
                'description' => 'Een veel besproken onderwerp tijdens een dieet is natuurlijk het gebruik van alcohol. In het ene dieet wordt het toegelaten waarbij het in het andere dieet wordt verboden.',
                'component' => 'AlcoholEnAfvallen',
                'featured_image' => '/assets/blog/alcohol-en-afvallen.jpg',
                'featured_image_webp' => '/assets/blog/webp/alcohol-en-afvallen.webp',
                'featured_image_alt' => 'Alcohol en afvallen',
            ],
            [
                'title' => 'Spijsvertering systeem: wat gebeurd er met een hap eten?',
                'slug' => 'spijsvertering-systeem',
                'description' => 'Ons darmkanaal regelt onze \'binnenwereld\'. De perfect uitgevoerde werkzaamheden starten bij de mond, het portaal naar de wereld van onze darmen.',
                'component' => 'SpijsverteringSysteem',
                'featured_image' => '/assets/blog/spijsvertering-systeem.jpg',
                'featured_image_webp' => '/assets/blog/webp/spijsvertering-systeem.webp',
                'featured_image_alt' => 'Spijsvertering systeem',
            ],
            [
                'title' => 'Mijn stofwisseling is vertraagd, wat nu?',
                'slug' => 'vertraagde-stofwisseling',
                'description' => 'Een van de grootste fouten die wordt gemaakt bij het afvallen is dat een vertraagde stofwisseling ontstaat. Hierdoor wordt het afvallen steeds moeilijker.',
                'component' => 'VertraagdeStofwisseling',
                'featured_image' => '/assets/blog/vertraagde-stofwisseling.jpg',
                'featured_image_webp' => '/assets/blog/webp/vertraagde-stofwisseling.webp',
                'featured_image_alt' => 'Vertraagde stofwisseling',
            ],
            [
                'title' => 'Appelazijn, het wonder om snel vet te verliezen?',
                'slug' => 'appelazijn',
                'description' => 'Wat zegt de wetenschap over appelazijn en wat doet het met onze gezondheid?',
                'component' => 'Appelazijn',
                'featured_image' => '/assets/blog/appelazijn.jpg',
                'featured_image_webp' => '/assets/blog/webp/appelazijn.webp',
                'featured_image_alt' => 'Appelazijn',
            ],
            [
                'title' => 'CLA: de wonderpil om af te vallen?',
                'slug' => 'cla',
                'description' => 'In deze blog gaan we het hebben over geconjugeerd linolzuur oftewel CLA. Dit populaire supplement wordt vaak gebruikt om extra gewicht te verliezen maar wat is er waar van deze theorie?',
                'component' => 'Cla',
                'featured_image' => '/assets/blog/cla.jpg',
                'featured_image_webp' => '/assets/blog/webp/cla.webp',
                'featured_image_alt' => 'CLA',
            ],
            [
                'title' => 'Pre-Workout: wat is het en wat doet het precies?',
                'slug' => 'pre-workout',
                'description' => 'De voornaamste reden voor het gebruiken van pre-workout is het bevorderen van de trainingen. Maar wat doet pre-workout nou precies en waarom zou je het wel of niet kunnen gebruiken?',
                'component' => 'PreWorkout',
                'featured_image' => '/assets/blog/pre-workout.jpeg',
                'featured_image_webp' => '/assets/blog/webp/pre-workout.webp',
                'featured_image_alt' => 'Pre-workout',
            ],
            [
                'title' => 'Vlees: gezond of gif?',
                'slug' => 'vlees',
                'description' => 'In deze blog openen we de discussie over het consumeren van vlees. Zijn we hier als mensen wel voor gemaakt en wat doet het met ons lichaam als we minder vlees zouden eten?',
                'component' => 'Vlees',
                'featured_image' => '/assets/blog/vlees.jpg',
                'featured_image_webp' => '/assets/blog/webp/vlees.webp',
                'featured_image_alt' => 'Vlees',
            ],
            [
                'title' => 'Resultaat meten aan de hand van lichaamsgewicht, verstandig of niet?',
                'slug' => 'resultaat-meten',
                'description' => 'Dit keer gaan we het over het resultaat meten aan de hand van lichaamsgewicht tijdens het afvallen. In deze blog gaan we dieper in op wat allemaal ons gewicht bepaalt.',
                'component' => 'ResultaatMeten',
                'featured_image' => '/assets/blog/resultaat-meten.jpg',
                'featured_image_webp' => '/assets/blog/webp/resultaat-meten.webp',
                'featured_image_alt' => 'Resultaat meten',
            ],
            [
                'title' => 'Stress: de \'silent killer\' voor onze vetverbranding!',
                'slug' => 'stress-de-silent-killer',
                'description' => 'Stress zorgt namelijk voor verhoogde cortisolwaarden in het lichaam wat negatieve gevolgen heeft op de vetverbranding.',
                'component' => 'StressDeSilentKiller',
                'featured_image' => '/assets/blog/stress.jpg',
                'featured_image_webp' => '/assets/blog/webp/stress.webp',
                'featured_image_alt' => 'Stress',
            ],
            [
                'title' => 'Genetische aanleg: feit of fabel?',
                'slug' => 'genetische-aanleg',
                'description' => 'In deze blog behandelen we het onderwerp genetisch aanleg. Na het lezen van deze blog weet je of de verhalen van invloed door genetica op je vet of spier waar zijn of fabels.',
                'component' => 'GenetischeAanleg',
                'featured_image' => '/assets/blog/genen.jpg',
                'featured_image_webp' => '/assets/blog/webp/genen.webp',
                'featured_image_alt' => 'Genetische aanleg',
            ],
            [
                'title' => 'Zink: hulpmiddel of overbodig?',
                'slug' => 'zink-als-hulpmiddel',
                'description' => 'Vandaag duiken we dieper in op zink om erachter te komen of zink een hulpmiddel is of overbodig.',
                'component' => 'ZinkAlsHulpmiddel',
                'featured_image' => '/assets/blog/zink.jpg',
                'featured_image_webp' => '/assets/blog/webp/zink.webp',
                'featured_image_alt' => 'Zink',
            ],
            [
                'title' => 'Tempo verschillen per herhaling, wat doet het?',
                'slug' => 'belang-van-tempo',
                'description' => 'In deze blog bespreken we een onderdeel uit de krachttraining, namelijk de snelheid van de herhalingen die we per set maken.',
                'component' => 'BelangVanTempo',
                'featured_image' => '/assets/blog/tempo.jpg',
                'featured_image_webp' => '/assets/blog/webp/tempo.webp',
                'featured_image_alt' => 'Tempo',
            ],
            [
                'title' => 'Snel een platte buik, is dat mogelijk?',
                'slug' => 'snel-een-platte-buik',
                'description' => 'Een van de meeste gehoorde wensen is het hebben van een platte buik. In deze blog leggen we uit wat de oorzaken zijn van een bolle buik en hoe je een platte buik kan krijgen.',
                'component' => 'SnelEenPlatteBuik',
                'featured_image' => '/assets/blog/platte-buik.jpg',
                'featured_image_webp' => '/assets/blog/webp/platte-buik.webp',
                'featured_image_alt' => 'Platte buik',
            ],
            [
                'title' => 'Cellulite: genetisch of te behandelen?',
                'slug' => 'cellulite',
                'description' => 'Cellulite is iets waar veel vrouwen mee worstelen en willen hier graag vanaf. In deze blog gaan we hier dieper op in.',
                'component' => 'Cellulite',
                'featured_image' => '/assets/blog/cellulite.jpg',
                'featured_image_webp' => '/assets/blog/webp/cellulite.webp',
                'featured_image_alt' => 'Cellulite',
            ],
            [
                'title' => 'Menopauze, en nu?',
                'slug' => 'menopauze',
                'description' => 'In deze blog lees je alles over de menopauze. We gaan dieper in op wat de menopauze is, de meest voorkomende klachten en hoe je dit kunt oplossen.',
                'component' => 'Menopauze',
                'featured_image' => '/assets/blog/menopauze.jpg',
                'featured_image_webp' => '/assets/blog/webp/menopauze.webp',
                'featured_image_alt' => 'Menopauze',
            ],
            [
                'title' => 'Progressieve overload, de sleutel tot groei!',
                'slug' => 'progressieve-overload',
                'description' => 'In deze blog gaan we dieper in op progressieve overload. Dit trainingsprincipe is belangrijk voor iedereen die wil afvallen of gespierder wil worden!',
                'component' => 'ProgressieveOverload',
                'featured_image' => '/assets/blog/progressieve-overload.jpg',
                'featured_image_webp' => '/assets/blog/webp/progressieve-overload.webp',
                'featured_image_alt' => 'Progressieve overload',
            ],
            [
                'title' => 'Plaatselijk (buik)vet verbranden, is het mogelijk?',
                'slug' => 'plaatselijk-vet-verbranden',
                'description' => 'We krijgen vaak de vraag of het mogelijk is om, voornamelijk buikvet plaatselijk te verbranden. Of dit mogelijk is bespreken we in deze blog.',
                'component' => 'PlaatselijkVetVerbranden',
                'featured_image' => '/assets/blog/plaatselijk-vet-verbranden.jpg',
                'featured_image_webp' => '/assets/blog/webp/plaatselijk-vet-verbranden.webp',
                'featured_image_alt' => 'Plaatselijk vet verbranden',
            ],
            [
                'title' => 'Hoe snel kun je spiermassa laten groeien?',
                'slug' => 'spiermassa-laten-groeien',
                'description' => 'Dit keer richten we op alle krachtsporters die graag meer spiermassa willen. Veel van deze krachtsporters zullen het wel merken dat je na een aantal maanden trainen niet meer dezelfde groei maakt.',
                'component' => 'SpiermassaLatenGroeien',
                'featured_image' => '/assets/blog/spiermassa-laten-groeien.jpg',
                'featured_image_webp' => '/assets/blog/webp/spiermassa-laten-groeien.webp',
                'featured_image_alt' => 'Spiermassa laten groeien',
            ],
            [
                'title' => 'Hoe voorkom je honger?',
                'slug' => 'honger-voorkomen',
                'description' => 'Honger is een vervelend gevoel. Je maag begint hard te rammelen en krampen te krijgen. Hoe komt het dat we honger krijgen en hoe voorkomen we het?',
                'component' => 'HongerVoorkomen',
                'featured_image' => '/assets/blog/honger-voorkomen.jpg',
                'featured_image_webp' => '/assets/blog/webp/honger-voorkomen.webp',
                'featured_image_alt' => 'Honger',
            ],
            [
                'title' => 'Waarom je geen multivitaminen hoeft te nemen als je voldoende groente en fruit eet',
                'slug' => 'geen-multivitaminen-voldoende-fruit',
                'description' => 'Groente en fruit leveren niet alleen essentiële voedingsstoffen, maar ook antioxidanten die helpen bij het herstel van spieren na een intensieve training.',
                'component' => 'GeenMultivitaminenVoldoendeFruit',
                'featured_image' => '/assets/blog/multivitaminen-groente-fruit.jpg',
                'featured_image_webp' => '/assets/blog/webp/multivitaminen-groente-fruit.webp',
                'featured_image_alt' => 'Multivitaminen',
            ],
            [
                'title' => 'Vijf redenen om meer krachttraining te doen',
                'slug' => 'vijf-redenen-om-meer-krachttraining-te-doen',
                'description' => 'Krachttraining heeft talloze voordelen die verder gaan dan het opbouwen van spiermassa en het krijgen van een gespierd uiterlijk.',
                'component' => 'VijfRedenenOmMeerKrachttrainingTeDoen',
                'featured_image' => '/assets/blog/meer-krachttraining.jpg',
                'featured_image_webp' => '/assets/blog/webp/meer-krachttraining.webp',
                'featured_image_alt' => 'Krachttraining',
            ],
            [
                'title' => 'Vijf redenen waarom vasten mogelijk een goed idee is voor sporters',
                'slug' => 'vijf-redenen-waarom-vasten-mogelijk-een-goed-idee-is-voor-sporters',
                'description' => 'Een methode die de laatste jaren steeds meer aandacht krijgt, is vasten. Vasten kan verschillende vormen aannemen, zoals intermittent fasting of periodiek vasten.',
                'component' => 'VijfRedenenVasten',
                'featured_image' => '/assets/blog/vasten.jpg',
                'featured_image_webp' => '/assets/blog/webp/vasten.webp',
                'featured_image_alt' => 'Vasten',
            ],
            [
                'title' => 'Top tien voedselproducten met het hoogste eiwitgehalte',
                'slug' => 'top-tien-voedselproducten-met-het-hoogste-eiwitgehalte',
                'description' => 'Als sporter is het belangrijk om voldoende eiwitten binnen te krijgen voor spierherstel en -opbouw. Eiwitten zijn namelijk de bouwstenen van onze spieren.',
                'component' => 'TopTienEiwitgehalte',
                'featured_image' => '/assets/blog/top-10-voeding-eiwitgehalte.jpg',
                'featured_image_webp' => '/assets/blog/webp/top-10-voeding-eiwitgehalte.webp',
                'featured_image_alt' => 'Top tien voedselproducten met het hoogste eiwitgehalte',
            ],
            [
                'title' => 'Waarom het moeite kost om gewicht te verliezen tijdens de menstruatie',
                'slug' => 'waarom-het-moeite-kost-om-gewicht-te-verliezen-tijdens-de-menstruatie',
                'description' => 'Veel vrouwen merken dat het moeilijker is om gewicht te verliezen tijdens hun menstruatie. Maar waarom is dit eigenlijk zo?',
                'component' => 'GewichtVerliezenMenstruatie',
                'featured_image' => '/assets/blog/gewicht-verliezen-menstruatie.jpg',
                'featured_image_webp' => '/assets/blog/webp/gewicht-verliezen-menstruatie.webp',
                'featured_image_alt' => 'Gewicht verliezen tijdens de menstruatie',
            ],
            [
                'title' => 'De ultieme top 10: Voedingsproducten rijk aan gezonde koolhydraten',
                'slug' => 'de-ultieme-top-10-voedingsproducten-rijk-aan-koolhydraten',
                'description' => 'In deze blogpost zullen we een diepgaande blik werpen op de top tien voedingsproducten die rijk zijn aan gezonde koolhydraten.',
                'component' => 'TopTienKoolhydraten',
                'featured_image' => '/assets/blog/koolhydraten.png',
                'featured_image_webp' => '/assets/blog/webp/koolhydraten.webp',
                'featured_image_alt' => 'Koolhydraten',
            ],
            [
                'title' => 'De Top Tien Voedingsproducten Rijk aan Gezonde Vetten',
                'slug' => 'de-top-tien-voedingsproducten-rijk-aan-gezonde-vetten',
                'description' => 'Gezonde vetten zijn een essentieel onderdeel van een evenwichtig dieet. Ze spelen een cruciale rol in tal van lichaamsfuncties.',
                'component' => 'TopTienGezondeVetten',
                'featured_image' => '/assets/blog/gezonde-vetten.png',
                'featured_image_webp' => '/assets/blog/webp/gezonde-vetten.webp',
                'featured_image_alt' => 'Gezonde vetten',
            ],
            [
                'title' => 'Vijf Manieren om Uw Bloedsuikerspiegel Stabiel te Houden',
                'slug' => 'vijf-manieren-om-uw-bloedsuikerspiegel-stabiel-te-houden',
                'description' => 'In deze blogpost onthullen we vijf effectieve manieren om uw bloedsuikerspiegel stabiel te houden.',
                'component' => 'BloedsuikerspiegelStabiel',
                'featured_image' => '/assets/blog/bloedsuikerspiegel.png',
                'featured_image_webp' => '/assets/blog/webp/bloedsuikerspiegel.webp',
                'featured_image_alt' => 'Bloedsuikerspiegel',
            ],
            [
                'title' => 'De kracht van gezond eten en krachttraining bij een vertraagde schildklier',
                'slug' => 'de-kracht-van-gezond-eten-en-krachttraining-bij-een-vertraagde-schildklier',
                'description' => 'Wanneer u zich voortdurend vermoeid voelt, moeite heeft met afvallen of last heeft van een droge huid, kan het zijn dat uw schildklier niet optimaal functioneert.',
                'component' => 'VertraagdeSchildklier',
                'featured_image' => '/assets/blog/vertraagde-schildklier.jpg',
                'featured_image_webp' => '/assets/blog/webp/vertraagde-schildklier.webp',
                'featured_image_alt' => 'Vertraagde schildklier',
            ],
            [
                'title' => 'Waarom een crash dieet niet de oplossing is voor gewichtsverlies',
                'slug' => 'waarom-een-crash-dieet-niet-de-oplossing-is-voor-gewichtsverlies',
                'description' => 'Onderzoek heeft aangetoond dat crash diëten op de lange termijn niet effectief zijn en zelfs schadelijk kunnen zijn voor uw gezondheid.',
                'component' => 'CrashDieet',
                'featured_image' => '/assets/blog/crashdieet.png',
                'featured_image_webp' => '/assets/blog/webp/crashdieet.webp',
                'featured_image_alt' => 'Crashdieet',
            ],
            [
                'title' => 'Ontdek de kracht van thermogenese voor een top shape!',
                'slug' => 'ontdek-de-kracht-van-thermogenese-voor-een-top-shape',
                'description' => 'Wist u dat het voedsel dat u eet, een cruciale rol kan spelen in uw streven om gewicht te verliezen? Het gaat allemaal om een fascinerend proces genaamd thermogenese.',
                'component' => 'Thermogenese',
                'featured_image' => '/assets/blog/thermogenese.png',
                'featured_image_webp' => '/assets/blog/webp/thermogenese.webp',
                'featured_image_alt' => 'Thermogenese',
            ],
            [
                'title' => 'De Magische Wereld van Vezels',
                'slug' => 'de-magische-wereld-van-vezels',
                'description' => 'Vezels zijn kleine superhelden die in je eten rondhangen en je lichaam helpen om als een geoliede machine te werken.',
                'component' => 'WereldVanVezels',
                'featured_image' => '/assets/blog/wereld-van-vezels.png',
                'featured_image_webp' => '/assets/blog/webp/wereld-van-vezels.webp',
                'featured_image_alt' => 'Vezels',
            ],
            [
                'title' => 'De wereld van cafeïne: een blik op de gezondheidsvoordelen!',
                'slug' => 'de-wereld-van-cafeine-een-blik-op-de-gezondheidsvoordelen',
                'description' => 'Van je ochtendkoffie tot die energiedrankjes die je helpen de nacht door te komen, cafeïne is overal om ons heen. Maar wat is cafeïne eigenlijk?',
                'component' => 'WereldVanCafeine',
                'featured_image' => '/assets/blog/cafeine.jpg',
                'featured_image_webp' => '/assets/blog/webp/cafeine.webp',
                'featured_image_alt' => 'Cafeïne',
            ],
            [
                'title' => 'Ontdek de kracht van Mateïne: Het alternatief voor cafeïne',
                'slug' => 'ontdek-de-kracht-van-mateine-het-alternatief-voor-cafeine',
                'description' => 'Mateïne is een natuurlijk stimulerend middel dat voorkomt in de yerba mate plant. Het is vergelijkbaar met cafeïne, maar dan zonder de nadelen.',
                'component' => 'KrachtVanMateine',
                'featured_image' => '/assets/blog/mateine.png',
                'featured_image_webp' => '/assets/blog/webp/mateine.webp',
                'featured_image_alt' => 'Mateïne',
            ],
            [
                'title' => 'Gedragsverandering: Jouw Sleutel tot Duurzaam Succes bij het Afvallen',
                'slug' => 'gedragsverandering-jouw-sleutel-tot-duurzaam-succes-bij-het-afvallen',
                'description' => 'We hebben het niet over een tijdelijke verandering, maar een duurzame transformatie. Laten we het hebben over gedragsverandering bij het afvallen.',
                'component' => 'Gedragsverandering',
                'featured_image' => '/assets/blog/gedragsverandering.jpg',
                'featured_image_webp' => '/assets/blog/webp/gedragsverandering.webp',
                'featured_image_alt' => 'Gedragsverandering',
            ],
            [
                'title' => 'Ontbijten, essentieel of niet?',
                'slug' => 'ontbijten-essentieel-of-niet',
                'description' => 'Is het ontbijt echt de belangrijkste maaltijd van de dag, of is het gewoon een slimme marketingtruc?',
                'component' => 'OntbijtenEssentieelOfNiet',
                'featured_image' => '/assets/blog/ontbijt.png',
                'featured_image_webp' => '/assets/blog/webp/ontbijt.webp',
                'featured_image_alt' => 'Ontbijt',
            ],
            [
                'title' => 'Waarom een Personal Trainer je investering waard is',
                'slug' => 'waarom-een-personal-trainer-je-investering-waard-is',
                'description' => 'Waarom zou je jouw fitnessreis alleen aangaan, als je een personal trainer kan hebben die je naar de top begeleidt?',
                'component' => 'PersonalTrainerInvestering',
                'featured_image' => '/assets/blog/personal-training.jpg',
                'featured_image_webp' => '/assets/blog/webp/personal-training.webp',
                'featured_image_alt' => 'Personal trainer',
            ],
            [
                'title' => 'Het belang van Vitamine D, en speciaal Vitamine D3',
                'slug' => 'het-belang-van-vitamine-d',
                'description' => 'Misschien heb je er al wel eens van gehoord, maar weet je ook waarom Vitamine D zo belangrijk is voor je lichaam?',
                'component' => 'BelangVanVitamineD',
                'featured_image' => '/assets/blog/vitamine-d.jpg',
                'featured_image_webp' => '/assets/blog/webp/vitamine-d.webp',
                'featured_image_alt' => 'Vitamine D',
            ],
            [
                'title' => 'De magische kracht van muziek tijdens je krachttraining',
                'slug' => 'de-magische-kracht-van-muziek-tijdens-je-krachttraining',
                'description' => 'Muziek kan je krachttraining daadwerkelijk naar een hoger niveau tillen. Laten we eens kijken waarom muziek je helpt bij krachttraining.',
                'component' => 'KrachtVanMuziek',
                'featured_image' => '/assets/blog/muziek.png',
                'featured_image_webp' => '/assets/blog/webp/muziek.webp',
                'featured_image_alt' => 'Muziek',
            ],
            [
                'title' => 'Hoe overleef je de Kerst zonder Extra Kilootjes?',
                'slug' => 'hoe-overleef-je-de-kerst-zonder-extra-kilootjes',
                'description' => 'Hoe zorg je ervoor dat je na de feestdagen niet met een kledingmaatje meer aan de slag moet?',
                'component' => 'KerstZonderKilootjes',
                'featured_image' => '/assets/blog/kerst.jpg',
                'featured_image_webp' => '/assets/blog/webp/kerst.webp',
                'featured_image_alt' => 'Kerst',
            ],
            [
                'title' => 'Kickstart je dag met een lach: Drie gezonde ontbijtrecepten',
                'slug' => 'kickstart-je-dag-met-een-lach',
                'description' => 'Zet je schrap voor drie gezonde ontbijtrecepten die je dag zullen kickstarten met een lach!',
                'component' => 'KickstartJeDag',
                'featured_image' => '/assets/blog/kickstart-ontbijt.png',
                'featured_image_webp' => '/assets/blog/webp/kickstart-ontbijt.webp',
                'featured_image_alt' => 'Ontbijt',
            ],
            [
                'title' => 'Hoe je een feestje bouwt zonder de kater: Drie alcoholvrije cocktails',
                'slug' => 'hoe-je-een-feestje-bouwt-zonder-de-kater',
                'description' => 'Recepten voor alcoholvrije cocktails die zo lekker zijn dat zelfs je lever je een staande ovatie zal geven.',
                'component' => 'FeestjeZonderKater',
                'featured_image' => '/assets/blog/feestje.png',
                'featured_image_webp' => '/assets/blog/webp/feestje.webp',
                'featured_image_alt' => 'Feestje',
            ],
            [
                'title' => 'Nieuw jaar, nieuw jij: een realistische kijk op (duurzame) goede voornemens!',
                'slug' => 'nieuw-jaar-nieuw-jij',
                'description' => 'Hoe scheid je de zin van de onzin als het gaat om effectieve manieren om gewicht te verliezen?',
                'component' => 'NieuwJaarNieuwJij',
                'featured_image' => '/assets/blog/voornemens.png',
                'featured_image_webp' => '/assets/blog/webp/voornemens.webp',
                'featured_image_alt' => 'Voornemens',
            ],
            [
                'title' => 'Het belang van omega 3-vetzuren in de strijd tegen diabetes',
                'slug' => 'belang-omega-3-bij-diabetes',
                'description' => 'Omega 3-vetzuren spelen een niet te onderschatten rol bij diabetes. In dit artikel duiken we in de wetenschap achter omega 3 en de impact ervan op diabetes.',
                'component' => 'Omega3BijDiabetes',
                'featured_image' => '/assets/blog/omega-3.png',
                'featured_image_webp' => '/assets/blog/webp/omega-3.webp',
                'featured_image_alt' => 'Omega 3',
            ],
            [
                'title' => 'Hoe je carnaval overleeft zonder extra kilo\'s als souvenir',
                'slug' => 'hoe-overleef-je-carnaval',
                'description' => 'Hier zijn vijf manieren om carnaval te vieren en toch vrienden te blijven met je broekriem.',
                'component' => 'CarnavalOverleven',
                'featured_image' => '/assets/blog/carnaval-breda-2019.jpg',
                'featured_image_webp' => '/assets/blog/webp/carnaval-breda-2019.webp',
                'featured_image_alt' => 'Carnaval',
            ],
            [
                'title' => 'De kunst van het omgaan met spierpijn: een wetenschappelijke benadering',
                'slug' => 'omgaan-met-spierpijn',
                'description' => 'Laten we eens duiken in de wetenschap achter spierpijn en ontdekken hoe we dit beestje bij de naam kunnen noemen en effectief kunnen temmen.',
                'component' => 'OmgaanMetSpierpijn',
                'featured_image' => '/assets/blog/spierpijn.jpg',
                'featured_image_webp' => '/assets/blog/webp/spierpijn.webp',
                'featured_image_alt' => 'Spierpijn',
            ],
            [
                'title' => 'Waarom voedsel preppen essentieel is voor gewichtsverlies',
                'slug' => 'voedsel-preppen',
                'description' => 'Laten we dieper duiken in waarom het preppen van voedsel zo\'n cruciale rol speelt in gewichtsverlies.',
                'component' => 'VoedselPreppen',
                'featured_image' => '/assets/blog/preppen.jpg',
                'featured_image_webp' => '/assets/blog/webp/preppen.webp',
                'featured_image_alt' => 'Preppen',
            ],
            [
                'title' => 'Krachttraining: de feiten en fabels op een rij',
                'slug' => 'krachttraining-feiten-fabels',
                'description' => 'Wat is nu echt waar over krachttraining? En wat kunnen we gerust naar het rijk der fabelen verwijzen?',
                'component' => 'KrachttrainingFeitenFabels',
                'featured_image' => '/assets/blog/krachttraining-feiten-fabels.jpg',
                'featured_image_webp' => '/assets/blog/webp/krachttraining-feiten-fabels.webp',
                'featured_image_alt' => 'Krachttraining',
            ],
            [
                'title' => 'De spaarstand van het lichaam: feit of fabel?',
                'slug' => 'spaarstand-van-het-lichaam',
                'description' => 'Wat houdt de spaarstand precies in? Is het een wetenschappelijk onderbouwd fenomeen of eerder een mythe?',
                'component' => 'SpaarstandVanHetLichaam',
                'featured_image' => '/assets/blog/spaarstand.jpg',
                'featured_image_webp' => '/assets/blog/webp/spaarstand.webp',
                'featured_image_alt' => 'Spaarstand',
            ],
            [
                'title' => 'Eiwitten ontwarren',
                'slug' => 'eiwitten-ontwarren',
                'description' => 'Vandaag duiken we in de verschillen tussen twee populaire vormen: whey en caseïne.',
                'component' => 'EiwittenOntwarren',
                'featured_image' => '/assets/blog/eiwitten-ontwarren.jpg',
                'featured_image_webp' => '/assets/blog/webp/eiwitten-ontwarren.webp',
                'featured_image_alt' => 'Eiwitten',
            ],
            [
                'title' => 'Ontdek de kracht van MCT olie',
                'slug' => 'kracht-van-mct-olie',
                'description' => 'Wat maakt MCT olie zo speciaal? En belangrijker, wat zegt de wetenschap erover?',
                'component' => 'KrachtVanMctOlie',
                'featured_image' => '/assets/blog/mct-olie.jpg',
                'featured_image_webp' => '/assets/blog/webp/mct-olie.webp',
                'featured_image_alt' => 'MCT olie',
            ],
            [
                'title' => 'De wonderbaarlijke invloed van rode bietensap op een hoge bloeddruk',
                'slug' => 'rode-bietensap-en-hoge-bloeddruk',
                'description' => 'In dit artikel duiken we in de wetenschappelijke onderbouwing achter de invloed van rode bietensap op een hoge bloeddruk.',
                'component' => 'RodeBietensapEnHogeBloeddruk',
                'featured_image' => '/assets/blog/rode-bietensap.jpg',
                'featured_image_webp' => '/assets/blog/webp/rode-bietensap.webp',
                'featured_image_alt' => 'Rode bietensap',
            ],
            [
                'title' => 'De verborgen impact van slaap op je eetgedrag',
                'slug' => 'impact-slaap-op-eetgedrag',
                'description' => 'In dit artikel duiken we dieper in hoe slaaptekort ons eetpatroon beïnvloedt, gesteund door wetenschappelijke inzichten.',
                'component' => 'ImpactSlaapOpEetgedrag',
                'featured_image' => '/assets/blog/slaap-eetgedrag.jpg',
                'featured_image_webp' => '/assets/blog/webp/slaap-eetgedrag.webp',
                'featured_image_alt' => 'Slaap en eetgedrag',
            ],
            [
                'title' => 'Hoe snel kun je spiermassa opbouwen en verliezen?',
                'slug' => 'hoe-snel-kun-je-spiermassa-opbouwen-en-verliezen',
                'description' => 'In deze blog duiken we in de wetenschap achter spiergroei en -verlies, en geven we je praktische tips om je spiermassa te maximaliseren.',
                'component' => 'SpiermassaOpbouwenEnVerliezen',
                'featured_image' => '/assets/blog/spiermassa-opbouwen.jpg',
                'featured_image_webp' => '/assets/blog/webp/spiermassa-opbouwen.webp',
                'featured_image_alt' => 'Spiermassa opbouwen',
            ],
            [
                'title' => 'De onverwachte gevolgen van stoppen met roken: Hoe je metabolisme verandert',
                'slug' => 'onverwachte-gevolgen-van-stoppen-met-roken',
                'description' => 'In dit artikel duiken we dieper in de relatie tussen stoppen met roken en je metabolisme.',
                'component' => 'GevolgenStoppenMetRoken',
                'featured_image' => '/assets/blog/gevolgen-stoppen-roken.jpg',
                'featured_image_webp' => '/assets/blog/webp/gevolgen-stoppen-roken.webp',
                'featured_image_alt' => 'Stoppen met roken',
            ],
            [
                'title' => 'Spiergeheugen bij krachttraining: mythe of realiteit?',
                'slug' => 'spiergeheugen-bij-krachttraining',
                'description' => 'Bestaat spiergeheugen echt, en zo ja, hoe werkt het dan? In dit artikel duiken we dieper in de wetenschap achter spiergeheugen.',
                'component' => 'SpiergeheugenBijKrachttraining',
                'featured_image' => '/assets/blog/spiergeheugen.jpg',
                'featured_image_webp' => '/assets/blog/webp/spiergeheugen.webp',
                'featured_image_alt' => 'Spiergeheugen',
            ],
            [
                'title' => 'Krachttraining tijdens de zwangerschap: veilig en effectief',
                'slug' => 'krachttraining-tijdens-zwangerschap',
                'description' => 'Met de juiste aanpak kan krachttraining tijdens de zwangerschap niet alleen veilig zijn, maar ook vele voordelen bieden.',
                'component' => 'KrachttrainingTijdensZwangerschap',
                'featured_image' => '/assets/blog/zwanger.jpg',
                'featured_image_webp' => '/assets/blog/webp/zwanger.webp',
                'featured_image_alt' => 'Zwanger',
            ],
            [
                'title' => 'De stille epidemie: overgewicht en buikomvang in Nederland',
                'slug' => 'de-stille-epidemie',
                'description' => 'Maar liefst de helft van de Nederlandse bevolking kampt met overgewicht. Laten we eens dieper ingaan op de gevaren van overgewicht.',
                'component' => 'DeStilleEpidemie',
                'featured_image' => '/assets/blog/stille-epidemie.png',
                'featured_image_webp' => '/assets/blog/webp/stille-epidemie.webp',
                'featured_image_alt' => 'Stille epidemie',
            ],
            [
                'title' => 'Trainen op hartslag voor optimale vetverbranding: zo pak je het aan',
                'slug' => 'trainen-op-hartslag-voor-optimale-vetverbranding',
                'description' => 'Trainen op hartslag is een uitstekende methode om vet te verbranden. In dit artikel leer je hoe je je optimale hartslagzone berekent.',
                'component' => 'TrainenOpHartslag',
                'featured_image' => '/assets/blog/trainen-op-hartslag.jpg',
                'featured_image_webp' => '/assets/blog/webp/trainen-op-hartslag.webp',
                'featured_image_alt' => 'Trainen op hartslag',
            ],
        ];
    }

    /**
     * @return array{title: string, slug: string, description: string, component: string, featured_image: string, featured_image_webp: string, featured_image_alt: string}|null
     */
    public static function findBySlug(string $slug): ?array
    {
        return collect(self::get())->firstWhere('slug', $slug);
    }
}
